name: Check the Program
run-name: Check the formatting and code
on: [push]
jobs:
  check:
    runs-on: ubuntu-24.04
    container:
      image: node:20
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
    - name: Install the App
      run: yarn install
      shell: bash
    - name: Check the formatting
      run: yarn run prettier --check
      shell: bash
    - name: Lint the App
      run: yarn lint
      shell: bash
    - name: Build the App
      run: yarn build
      shell: bash
    - name: Test the App
      run: yarn test
      shell: bash
