name: Vacuum open API linting 
run-name: Linting OpenAPI spec with Vacuum
on: [push]
jobs:
  vacuum-lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Lint specs with Vacuum
      run: curl -fsSL https://quobix.com/scripts/install_vacuum.sh | sh && vacuum lint specs/*
      shell: bash
